---
- hosts: server2
  become: true
  tasks:
    - name: Make sure that we can connect to the machine
      ping:
    - name: Install required packages
      apt: name={{item}} state=present update_cache=yes allow_unauthenticated=yes
      with_items:
      - php5-cli
      - nginx
      - mysql-server-5.6
    - name: Add the ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php'
    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install PHP
      apt: name={{item}} state=installed
      with_items:
      - php
      - php-fpm
      - php-mysql
      - php-xml
    - name: Remove apache2
      apt: name=apache2 state=removed
    - name: Install MySQL
      apt: name={{item}} state=installed
      with_items:
        - mysql-server-5.6
        - python-mysqldb
    - name: Generate new root password
      command: openssl rand -hex 7
      register: mysql_new_root_pass
    - name: Remove anonymous users
      mysql_user: name="" state=absent
    - name: Remove test database
      mysql_db: name=test state=absent
    - name: Update root password
      mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
      with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
    - name: Output new root password
      debug: msg="New root password is {{mysql_new_root_pass.stdout}}"

- hosts: server2
  become: true
  tasks:
        - name: Make sure that we can connect to the machine
          ping:
