version: '2'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
     - 8081:8081
     - /vagrant_data/nexus-data:/nexus-data
    restart: always
  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity
    ports:
     - 8111:8111
    depends_on:
     - nexus
    links:
     - nexus
    volumes:
     - /vagrant_data/tc-data/data/data/teamcity_server/datadir
     - /vagrant_data/tc-data/logs:/opt/teamcity/logs
    restart: always
