---
- hosts: all
  become: true
  tasks:
    - name: Make sure that we can connect to the machine
      ping:
    - name: Install required packages
      apt: name={{item}} state=present update_cache=yes allow_unauthenticated=yes
      with_items:
      - php5-cli
      - nginx
      - mysql-server-5.6
